### ISSUE TITLE
I got Error when I handle SSR cases, not able to find how to fix it 

### ISSUE THREAD

**Issue by NikhilMasurkar** [igordanchenko/yet-another-react-lightbox#176]
### Describe the bug

I handle the SSR cases in my website then i got one error 

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Project_Repo\Website\client\node_modules\yet-another-react-lightbox\dist\index.js

### Expected behavior

N/A

### How to reproduce

[nodemon] restarting due to changes...
[nodemon] starting `babel-node -r dotenv/config ./server/index.js`
redux-persist failed to create sync storage. falling back to noop storage.
[nodemon] restarting due to changes...
[nodemon] starting `babel-node -r dotenv/config ./server/index.js`
redux-persist failed to create sync storage. falling back to noop storage.
internal/modules/cjs/loader.js:1102
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Project_Repo\Website\client\node_modules\yet-another-react-lightbox\dist\index.js
require() of ES modules is not supported.
require() of C:\Project_Repo\Website\client\node_modules\yet-another-react-lightbox\dist\index.js from C:\Project_Repo\Website\client\src\app\pages\sharedComponents\IL\ILImageViewer.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Project_Repo\Website\client\node_modules\yet-another-react-lightbox\package.json.

    at Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Object.newLoader [as .js] (C:\Project_Repo\Website\client\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Project_Repo\Website\client\src\app\pages\sharedComponents\IL\/ILImageViewer.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (C:\Project_Repo\Website\client\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by igordanchenko** [comment]
What kind of framework / bundler are you using?
